name: "elixir-composite-ci-action"
description: "A composite ci action for elixir."
inputs:
  github_job:
    description: "GITHUB JOB. Default: `github.job`"
    default: '${{ github.job }}'
    required: false
  cache_version:
    description: "CACHE VERSION"
    required: false
    default: "0"
  mix_env:
    description: "MIX ENV"
    required: false
    default: "test"
  pat:
    description: "PERSINAL ACCESS TOKEN"
    required: true

runs:
  using: "composite"
  steps:
    - name: Run id
      id: get_run_id
      shell: bash
      run: |
        echo ::set-output name=JOB::${{ github.job }}
        START_TIME=$(date +%s)
        echo ::set-output name=START_TIME::$START_TIME
